trigger:
  - Caregiver-Dashboard

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: npm install
    displayName: 'Install dependencies'

  - script: npm run build
    displayName: 'Build React application'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: 'drop'
      publishLocation: 'container'